### ISSUE TITLE
Ability to change text in payment method

### ISSUE THREAD

**Issue by kornpow** [ZapriteApp/zaprite-for-woocommerce#31]
Currently the text "Powered by Zaprite" is hardcoded and not able to be editted. I want to provide more info here so people know that this single payment method allows many other payment methods once selecting it. I have modified the code for my usage, but it would be better if the official plugin allowed it.

<img width="1130" alt="image" src="https://github.com/ZapriteApp/zaprite-for-woocommerce/assets/3485377/0a3744aa-4c90-4db6-a403-2b95ed8c0c7b">

**Comment by john-zaprite** [comment]
We added the ability to edit the _Payment Method Name_ for this reason. 

Does this work for you?

<img width="889" alt="woo-zaprite-plugin" src="https://github.com/ZapriteApp/zaprite-for-woocommerce/assets/12265052/ceb03989-17a6-4c78-ad35-cd3b04db3999">

<img width="1052" alt="woo-checkout" src="https://github.com/ZapriteApp/zaprite-for-woocommerce/assets/12265052/85c4bbd4-6f8d-492b-96db-c24eaa6dec07">

**Comment by kornpow** [comment]
yeah, actually that works just fine!
